//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaBookingSYstemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBooking
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public decimal mobile { get; set; }
        public System.DateTime date { get; set; }
        public string address { get; set; }
    }
}
